input_data:
  input_path: input_data\Input P1 AND P2.xlsx
  P1_delete_top_rows: 6
  P2_delete_top_rows: 0

timeseries:
  start_year: 1997
  end_year: 2020

output_file:
  output_path: output_data\Python Output P1_P2_RA_BB22.xlsx
  sheet_1_name: P1_RA_BB21
  sheet_2_name: P2_RA_BB21